### PR TITLE
 fixes #142 (App.jsx, BgColorSidePanel.jsx, canvas.js): The line draw…

### LINKED ISSUE #142: [BUG] The line drawn gets un centered from the cursor when drawing further downwards on the canvas.
**Describe the bug**

**To Reproduce**
1. Start drawing by pressing mouse down.
2. Drag the mouse while not releasing the mouse.
3. Let go of the mouse at end of canvas.
4. See the cursor move away from the end of the drawn line.

**Expected behavior**
The corresponding line should be drawn at the center of the cursor and should follow it accurately until the mouse pressed is left.

**Video**
https://github.com/singodiyashubham87/Draw-it-out/assets/92173476/df6cb58c-6d0f-4f55-ac53-cd0b8d818d8e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave

### PR DESCRIPTION
**Pull request by mondalsurojit**
fixes #142 (App.jsx, BgColorSidePanel.jsx, canvas.js): The line drawn gets un centered from the cursor when drawing further downwards on the canvas

## Type of change ☑️

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Code style update (formatting, local variables)

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

https://github.com/singodiyashubham87/Draw-it-out/assets/114282267/ea7acfe1-dbb7-41a0-a4ba-fc3f91cf015a

### CODE REVIEW

**Comment by mondalsurojit** [comment]
@singodiyashubham87 Sir I request you to review my PR...and I hope you will consider this as a level 3 issue...as this issue remained unsolved for a long time and it also took around 2 days just to figure out where the problem actually is...but finally I solved it...thank you in advance...

File: src/App.jsx [hunk 1]
```diff
@@ -162,10 +160,9 @@ function App() {
 
             {/* ----- Canvas ------ */}
             <canvas
-              id="draw"
-              className={`whiteboard bg-slate-950 w-screen mt-[4vh] rounded-[0.6rem] shadow-md shadow-black dark:shadow-black dark:shadow-lg ${
-                isDrawing ? "cursor-crosshair" : "cursor-default pointer-events-none"
-              }
+              // id="draw"
+              className={`whiteboard bg-slate-950 rounded-[0.6rem] shadow-md shadow-black dark:shadow-black dark:shadow-lg ${isDrawing ? "cursor-crosshair" : "cursor-default pointer-events-none"
+                }
```
Comment (0xabdulkhalid) [inline src/App.jsx:165]: I would recommend you to remove `isDrawing` from `className`, because the `isDrawing` is always gonna be `true`. We don't need conditional rendering here.

So you can simply use `cursor-crosshair` for canvas `className`.

```suggestion
className="whiteboard bg-slate-950 rounded-[0.6rem] shadow-md shadow-black dark:shadow-black dark:shadow-lg cursor-crosshair"
```

**Review by 0xabdulkhalid — APPROVED** [review]

**Comment by 0xabdulkhalid** [comment]
> [!NOTE]
> BTW, I mistakenly approved changes. I was about to request changes!

**Comment by mondalsurojit** [comment]
@0xabdulkhalid I removed the extra conditional class...I hope now its okay...please see once...
@singodiyashubham87

File: src/App.jsx [hunk 2]
```diff
@@ -162,13 +160,9 @@ function App() {
...
             <canvas
-              id="draw"
-              className={`whiteboard bg-slate-950 w-screen mt-[4vh] rounded-[0.6rem] shadow-md shadow-black dark:shadow-black dark:shadow-lg ${
-                isDrawing ? "cursor-crosshair" : "cursor-default pointer-events-none"
-              }
-            `}
-              ref={canvasRef}
-            ></canvas>
+              // id="draw"
+              className={`whiteboard bg-slate-950 rounded-[0.6rem] shadow-md shadow-black dark:shadow-black dark:shadow-lg cursor-crosshair`}
```
Comment (0xabdulkhalid) [inline src/App.jsx:164]: You don't need to use backticks and curly brackets {``}.

React evaluates the expression inside the curly braces, even if it's just a static string, which involves a bit more processing.

It's not a best practice though, We only want to use backticks and curly braces when we need to include JavaScript expressions, such as conditional logic, variables, or template literals.

So, you need to use double quotes for static class names to avoid unnecessary processing.

Additionally you can remove the `id="draw"`, it's not needed.

You can copy paste the below suggestion,

```suggestion
className="whiteboard bg-slate-950 rounded-[0.6rem] shadow-md shadow-black dark:shadow-black dark:shadow-lg cursor-crosshair"
```

**Review by 0xabdulkhalid — CHANGES_REQUESTED** [review]

File: src/App.jsx (hunk 2 above)
Comment (mondalsurojit) [reply src/App.jsx]: I changed it now. Please check once, is it okay now...?

**Review by 0xabdulkhalid — APPROVED** [review]
Good to go 🚀 

@singodiyashubham87, now this PR is ready to be merged.

**Comment by singodiyashubham87** [comment]
@mondalsurojit Resolve the conflicts.

**Comment by mondalsurojit** [comment]
@singodiyashubham87 I have resolved the merge conflicts...now this branch is ready to be merged...

**Comment by singodiyashubham87** [comment]
@mondalsurojit Merge the main branch & push the changes.
# Your PR: 
image
# Actual
image

**Comment by singodiyashubham87** [comment]
@mondalsurojit While resolving the conflicts you have removed the code that was added by other PRs to solve other issues, which is not the correct way to resolve the conflicts, you have to modify your code according to the main branch & not remove the main branch's code to make your's one working.

There are many functionalities broken.
1. the tour steps are missing, there is only one tour step which tells about the color palette & then directly tells to start drawing
2. After selecting shapes, when we again select the pencil tool, it defaults it to solid brush & when we try to change to dotted or dashed, it does not change.
3. Improper UI, the cross button is overlapping the canvas & there is very less space between the canvas & tools container
image

**Comment by mondalsurojit** [comment]
@singodiyashubham87 Hello!
I had actually  checked everything before creating a PR, and everything was fine...Yes 2 bugs were noticed by me, which was caused due to some other previous PRs, and I believe those are directly or indirectly not connected to the code , I have written...

This is what my branch currently looks on my PC...
https://github.com/singodiyashubham87/Draw-it-out/assets/114282267/edd4072d-0e6d-4815-9a2c-28eb842f0c73

If you have saw my video, then you can see:
1) There are yet 3 steps, properly available one after the other in order. (p.s. still 1 step is missing, but I can't help, as that is caused due to some other problem)
2) (After selecting shapes, when we again select the pencil tool, it defaults it to solid brush & when we try to change to dotted or dashed, it does not change.) I have also demostrated this in the video.
3) The cursor on canvas is still a crosshair
4)The cross button is actually not overlapping...

I don't know, why you are facing such errors, on your side, it was not supposed to happen, as I have checked everything thoroughly before doing a PR (keeping aside 2 other bugs)....

Please check once, if everything is okay on your side

**Comment by mondalsurojit** [comment]
@singodiyashubham87 What I feel is that, when I am making a branch from "main" and someone else is also making a branch form "main"...Both of us are simultaneously working on an issue, but if I create PR before him, and then he tries to create PR, the code will break or create merge conflicts, and this is unavoidable...somehow the whole scenario looks like a race condition...
For the proper merging, such that there is minimum to no merge conflicts, the whole workflow should be serialized...only one person working at a time on a PR, and they should have a deadline....

**Comment by singodiyashubham87** [comment]
@mondalsurojit Maybe the UI change is because of OS resolution, You are working on Windows & I'm working on Linux.
I would recommend you to copy the changes that you made & create a new clone of the project in your local machine then paste the changes & create a new fresh PR, which won't have any conflicts with the merged PRs.

**Comment by singodiyashubham87** [comment]
@mondalsurojit working on this?

**Comment by mondalsurojit** [comment]
@singodiyashubham87 Please check once...If it doesn't work this time, I will create a new fork and try again...

**Comment by singodiyashubham87** [comment]
@mondalsurojit Conflicts, I recommend you to create a new fork.

**Comment by mondalsurojit** [comment]
@singodiyashubham87 I have resolved it, actually very minute conflicts, like a portion I had deleted, or a function's name that I had changed....Please see once

**Comment by singodiyashubham87** [comment]
@mondalsurojit I've reviewed your PR & here are some changes that you need to make:

1. The cursor is a pointer in the latest changes but your still has the crosshair
2. The gap between canvas & tools is not appropriate
# Actual:
image
# Yours one: 
image
3. In dark mode, the guidelines part looks different
# Actual:
image
# Yours: 
image

**Comment by singodiyashubham87** [comment]
@mondalsurojit Well Done, Keep contributing :)
